apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  # - host: traefik.local
  #   http:
  - http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 8001
        path: /dashboard
      - backend:
          serviceName: nginx-service
          servicePort: 8081
        path: /nginx