apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: dash.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 8081
