apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nginx
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          # servicePort: http
          servicePort: 31765